#!/usr/bin/env python3
"""Rebuild the English Fleet Commander acquisition pages; never touches GemGame."""
from pathlib import Path
import html,json
R=Path(__file__).resolve().parents[1]
BASE='https://georgepwall1991.github.io/fleet-commander-site/'
APP='https://apps.apple.com/us/app/fleet-commander-galaxy-war/id6760207805?uo=4'
BADGE='https://toolbox.marketingtools.apple.com/api/badges/download-on-the-app-store/black/en-gb?size=250x83'
def badge(campaign):
 return f'<a class="badge" href="{APP}&amp;ct={campaign}&amp;mt=8"><img src="{BADGE}" width="170" height="56" alt="Download on the App Store"></a>'
def head(title,description,route=''):
 schema={'@context':'https://schema.org','@type':'SoftwareApplication','name':'Fleet Commander','applicationCategory':'GameApplication','operatingSystem':'iOS 17.0 or later; iPadOS 17.0 or later','description':description,'url':BASE,'downloadUrl':APP,'offers':{'@type':'Offer','price':'0','priceCurrency':'USD'},'author':{'@type':'Person','name':'George Wall'}}
 return f'''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><meta name="description" content="{html.escape(description)}"><link rel="canonical" href="{BASE+route}"><meta property="og:type" content="website"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(description)}"><meta property="og:url" content="{BASE+route}"><meta property="og:image" content="{BASE}assets/frontier/social-card.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="{'../' if route else './'}assets/frontier/frontier.css"><script type="application/ld+json">{json.dumps(schema)}</script></head><body><a class="skip" href="#main">Skip to content</a>'''
def nav(prefix=''):
 return f'<header class="wrap nav"><a class="brand" href="{prefix or "./"}">FLEET<span>COMMANDER</span></a><nav aria-label="Main"><a href="{prefix}#gameplay">Gameplay</a><a href="{prefix}frontier-runs-guide/">Field guide</a><a href="{prefix}updates/">Updates</a></nav></header>'
def footer(prefix=''):
 return f'''<footer class="wrap"><div class="brand">FLEET COMMANDER</div><div class="links"><a href="{prefix}support/">Support</a><a href="{prefix}privacy/">Privacy</a><a href="{prefix}terms/">Terms</a><a href="{prefix}press/">Press kit</a><a href="{prefix}updates/">Updates</a><a href="{prefix}gemgame/">GemGame</a></div><p>© 2026 George Wall. Fleet Commander is free to download with optional in-app purchases. Research Lab subscriptions speed research by 25% in the conquest campaign. Admiral Supporter Pack liveries are cosmetic.</p><p>Also by George Wall — GemGame: Free to download, with no ads and no pay-to-win.</p></footer></body></html>'''
intro='Fleet Commander is a solo tactical space roguelite for iPhone and iPad. Explore the upcoming Frontier Runs update: fleet builds, rival commanders, and extraction.'
body=f'''<main id="main"><div class="hero"><div class="wrap hero-grid"><div><div class="release">FRONTIER RUNS · COMING IN 1.2.0</div><div class="eyebrow">A solo tactical space roguelite</div><h1>Your fleet.<br>Your <em>last word.</em></h1><p class="lead">A dangerous route. A rival waiting. Salvage you could lose. Build your fleet, read the battle, and decide how far to push.</p><div class="actions">{badge('frontier_home')}<a class="text-link" href="#gameplay">See the gameplay ↗</a></div><p class="small">iPhone &amp; iPad · Free with optional purchases<br>Download the current version. Frontier Runs footage previews the upcoming 1.2.0 update.</p></div><figure class="game-frame"><img src="assets/frontier/tactics.webp" width="1206" height="2622" alt="Frontier Runs tactical command choices: Blitz, Flank, and Fortify" fetchpriority="high"><figcaption>ACTUAL GAMEPLAY · UPCOMING VERSION 1.2.0</figcaption></figure></div></div><div class="wrap strip"><span>ONE FLEET. YOUR ORDERS.</span><span>TACTICAL BATTLES</span><span>MODULES + PROTOCOLS</span><span>PUSH ON OR EXTRACT</span></div>
<section class="wrap content"><div class="section-head"><div class="eyebrow">Command is a choice</div><h2>The next move<br>changes everything.</h2><p>Frontier Runs turns a sector into a series of decisions. Each route offers an opportunity. Each battle asks what you are willing to risk.</p></div><div class="grid"><article class="card"><span class="number">01 / READ THE FRONTIER</span><h3>Choose your next risk.</h3><p>Compare threats, rewards, and battlefield conditions. Take the route your fleet is built to survive.</p></article><article class="card"><span class="number">02 / FIND YOUR EDGE</span><h3>Make your build matter.</h3><p>Draft modules and protocols. Combine their effects, then choose Blitz, Flank, or Fortify to fit the fight.</p></article><article class="card"><span class="number">03 / KNOW WHEN TO LEAVE</span><h3>Bring the salvage home.</h3><p>Another encounter could change your run. Extract to bank your gains, or push on toward a rival commander.</p></article></div></section>
<div class="film-wrap"><section id="gameplay" class="wrap content film"><div><div class="eyebrow">Actual gameplay · upcoming 1.2.0</div><h2>Read it.<br>Call it.<br>Own the outcome.</h2><p class="lead">A closer look at the decisions inside a Frontier Run. Visible forecasts before the order. Battle receipts after it.</p><a href="frontier-runs-guide/">Read the beginner’s field guide ↗</a></div><video controls playsinline preload="none" poster="assets/frontier/tactics.webp" aria-label="Fleet Commander 1.2.0 gameplay preview"><source src="assets/frontier/frontier-preview.mp4" type="video/mp4"><a href="assets/frontier/frontier-preview.mp4">Watch the gameplay preview</a></video></section></div>
<section class="wrap content"><div class="eyebrow">The field guide</div><h2>Go in with a plan.</h2><div class="grid"><article class="card guide-card"><span class="number">THE GAME</span><h3><a href="space-roguelite/">What is a space roguelite?</a></h3><p>Understand the run, the tactical choices, and what connects one attempt to the next.</p></article><article class="card guide-card"><span class="number">YOUR FIRST RUN</span><h3><a href="frontier-runs-guide/">Make your first orders count.</a></h3><p>Routes, forecasts, rewards, and extraction—explained without the guesswork.</p></article><article class="card guide-card"><span class="number">BUILD + SURVIVE</span><h3><a href="fleet-builds-extraction/">Find your way home.</a></h3><p>Build around the modules you find and weigh your salvage against the next risk.</p></article></div></section><section class="content final"><div class="wrap"><div class="eyebrow">A new frontier is coming</div><h2>What will your last order be?</h2><p>Get Fleet Commander for iPhone and iPad. Frontier Runs arrives with the upcoming 1.2.0 update.</p><div class="actions">{badge('frontier_footer')}</div></div></section></main>'''
(R/'index.html').write_text(head('Fleet Commander: Space Roguelite & Tactical Fleet Battles',intro)+nav('./')+body+footer('./'))
articles=[
('space-roguelite/','A space roguelite. A fleet worth bringing home.','What is a space roguelite? Explore Fleet Commander’s upcoming Frontier Runs, tactical battles, fleet builds, extraction, and persistent legacy.','route',[
('What makes a Frontier Run?', 'In Fleet Commander 1.2.0, a Frontier Run takes your fleet through a sector of encounters. You choose routes, commit tactical orders, and adapt to the rewards you find. The appeal is the sequence of decisions: a useful module can change which battle you want next, while damage can turn an ambitious route into a reason to extract.'),
('Strategy at the point of command','Before a tactical encounter, inspect the visible forecast and compare Blitz, Flank, and Fortify. These are different commitments with different trade-offs. The right choice depends on your fleet, the opponent, and the current conditions. A strong forecast is information, not a guarantee; the battle receipt helps you understand the result.'),
('Your build changes your options','Modules and protocols influence battles and events. Some support a particular tactical order; others improve survivability or what you carry out. Build around what is available in the run. Finding a new combination is part of the experience, rather than following a single permanent upgrade checklist.'),
('The decision to extract','Salvage creates a reason to keep going and a reason to stop. Extraction banks your gains and ends that attempt. Continuing gives you access to further encounters and rival commanders, with the possibility of losing more integrity or ending the run in defeat. Returning with gains is a valid outcome.'),
('What carries forward?','Persistent reserves and fleet history connect your runs. Scars, repairs, and legacy choices give later decisions context. Frontier Runs is the solo tactical experience featured in this update; the older conquest campaign has its own research and prestige systems. The screenshots here show the upcoming 1.2.0 release, not the currently public 1.1.0 campaign.')]),
('frontier-runs-guide/','Your first Frontier Run: read, choose, commit.','A beginner guide to Fleet Commander Frontier Runs: choosing a route, reading tactical forecasts, drafting modules, and deciding when to extract.','tactics',[
('1. Read the route before you take it','Look at the encounter’s threat, reward, and battlefield conditions together. A tempting salvage reward does not tell the whole story. Consider your fleet’s current integrity and whether its modules support the kind of encounter ahead. If a wager is offered, read its objective and reward separately from the base encounter.'),
('2. Compare all three orders','Blitz, Flank, and Fortify expose forecasts and trade-offs before you commit. Compare what each order means for the present enemy. Do not assume your favourite order stays best throughout a run: rival intent, battlefield conditions, and your current modules can change the comparison.'),
('3. Read the battle receipt','After the battle, inspect the outcome, remaining integrity, and salvage. This is the useful moment to reassess your plan. A win can still leave your fleet damaged. Make the next route decision from the fleet you have now, rather than from the fleet you had at the beginning.'),
('4. Choose a reward with a purpose','When drafting, read the module or protocol’s rule text. A module that reinforces an order you can use effectively may be more valuable than an unrelated bonus. Alternatively, a defensive choice can preserve options if your integrity is low. There is no universal best pick across all routes and builds.'),
('5. Decide whether another encounter is worth it','Compare unbanked salvage, remaining integrity, and the next available route. Extract when protecting gains matters more than the next opportunity. Push deeper when you have a reason to accept the risk. A commander showdown deserves a fresh check of your forecast rather than an automatic repeat of the previous order.'),
('After the run','Review the debrief and your reserves. Fleet history gives the next attempt context; use what the last battle taught you when choosing your next build. These instructions describe the forthcoming 1.2.0 Frontier Runs update. The public download may still show the previous conquest campaign until Apple approves and the update is released.')]),
('fleet-builds-extraction/','Build for the fight. Plan for the way home.','Fleet Commander build guide: understand module combinations, tactical trade-offs, salvage, and extraction in the upcoming Frontier Runs update.','build',[
('Start with the module’s actual rule','Builds are about interactions. Read the rule text before deciding that a reward fits your fleet. Overkill Protocol rewards a winning Blitz with additional salvage; Wide Sweep rewards a winning Flank. These point toward different tactical preferences, but neither is a reason to ignore an unfavourable forecast.'),
('Separate winning from surviving','Ablative Screen reduces casualty bounds for Fortify, while Return Fire improves that order’s victory chance. Survival and victory are related but different goals. If the next encounter puts your remaining integrity at risk, examine both the forecast and the potential losses instead of selecting only the largest reward.'),
('Let a new module change the plan','Deep Scanner makes Flank treat route Danger as one lower. A reward like this can change the value of a route you previously wanted to avoid. Check the updated in-game forecast after drafting: it reflects the current encounter and build more usefully than a fixed build recipe.'),
('Know what is at stake','Unbanked salvage and persistent reserves are different. Extracting secures gains; continuing exposes the run to more encounters. Defeat does not follow a blanket lose-everything rule: the recovery rules and modules such as Black Box Cache affect what is banked. Read the current debrief rather than assuming all salvage was lost.'),
('Use extraction as part of the build','A profitable run does not have to end at the final showdown. If your modules generated salvage but left your fleet poorly suited to the next fight, extraction can be the coherent finish to that build. If your combination is still effective, continuing may be worth the risk. The decision belongs to you.'),
('Before a rival showdown','Re-read the enemy and its current stage. A multi-stage encounter can change what your next order needs to achieve. Adapt when the battle changes, then use the result and fleet history to inform the next run. All examples here refer to the upcoming 1.2.0 Frontier Runs release; in-game rule text remains the authority.')])]
for route,title,desc,scene,sections in articles:
 content=''.join(f'<section><h2>{html.escape(h)}</h2><p>{html.escape(p)}</p></section>' for h,p in sections)
 page=head(title+' | Fleet Commander',desc,route)+nav('../')+f'<main id="main" class="article"><div class="release">FIELD GUIDE · UPCOMING VERSION 1.2.0</div><h1>{html.escape(title)}</h1><p class="lead">{html.escape(desc)}</p><img src="../assets/frontier/{scene}.webp" alt="Actual Frontier Runs {scene} screen from version 1.2.0" width="1206" height="2622">'+content+f'<div class="actions">{badge("frontier_guide")}<a href="../frontier-runs-guide/">Beginner guide</a> · <a href="../fleet-builds-extraction/">Builds &amp; extraction</a> · <a href="../space-roguelite/">About the game</a></div></main>'+footer('../')
 d=R/route;d.mkdir(exist_ok=True);(d/'index.html').write_text(page)
print('Built Fleet Commander homepage and three guides')
